### ISSUE TITLE
Why not using bridge network?

### ISSUE THREAD

**Issue by link89** [taotaotheripper/Erlang-In-Docker#1]
I might be wrong, but won't that using docker bridge network make it possible that docker instances cross hosts are in same sub net?

**Comment by laheadle** [comment]
I had the same thought.

**Comment by Random-Liu** [comment]
In fact, I don't remember exactly. I just remember that at that time when I read the doc, docker just let me `link` containers with each other. That was 2 years ago... :)

Time flies... :(

**Comment by chulkilee** [comment]
Docker network feature was introduced at [1.9.0 (2015-11-03)](https://docs.docker.com/release-notes/docker-engine/#190-2015-11-03), so it was not available at that time :)
